#!/bin/bash

errexit() {
  echo ""
  echo "$1"
  echo ""
  echo "Usage: sudo pxe_copyslurmconf "
  echo ""
  exit 1
}

if [ $(id -u) -ne 0 ]; then
  errexit "Must be run as root user: sudo $0"
fi
for fn in `ls /pxe-root`
do
  cp -v /sharedfs/slurm.conf /pxe-root/$fn/etc/slurm/slurm.conf
done
cp -v /sharedfs/slurm.conf /etc/slurm/slurm.conf
